# Code auto-generated by leikinman
.data
.text
.globl	main
main:
	pushl %ebp
	movl %esp, %ebp
	subl $12, %esp
	movl $3, -4(%ebp)
	movl $4, -8(%ebp)
	movl $2, -12(%ebp)
	movl -4(%ebp), %eax
	addl -4(%ebp), %eax
	movl %ecx, %eax
	movl -4(%ebp), %eax
	imull -4(%ebp), %eax
	movl -4(%ebp), %ecx
	addl -8(%ebp), %ecx
	addl %ecx, %eax
	movl -8(%ebp), %edx
	addl -12(%ebp), %edx
	addl %edx, %eax
	addl %eax, %eax
	movl %eax, -4(%ebp)
	movl %ebp, %esp
	popl %ebp
	ret
